### ISSUE TITLE
[IDEA] Backup file name format

### ISSUE THREAD

**Issue by 1p0d** [DVDishka/Backuper#29]
Hey there, would be cool to have the option to provide a backup file name format. I'm using the `java.time` formats here.

Like this:
```yaml
backup:
  # (true/false) Automatic backup once in a specified period
  autoBackup: true
  # Set a format for backup file names (see java.time docs)
  backupFileNameFormat: "dd-MM-yyyy HH-mm-ss"
```

My use case: I want my file system to automatically sort backups. So `01-08-2024 18-11-49.zip` should be `2024-08-01 18-11-49.zip` to achieve this. Therefore, my `backupFileNameFormat` would be set to `"yyyy-MM-dd HH-mm-ss"`.
