### ISSUE TITLE
[HELP] Auto feature does not work

### ISSUE THREAD

**Issue by san-dingus** [DVDishka/Backuper#61]
I set up the config file according to the instructions provided but Backuper continues to not work.

Basically, I only have local storage enabled. I set backupPeriod to -1 and have tried setting backupTime to multiple values, but the one I'd like to use is 3. afterBackup is set to STOP (I have a restart script).

So essentially, the manual backups work perfectly. Doing /backuper backup local starts the task and completes it in about 10 minutes, saving it to the correct directory and everything. When I set the backupTime to a value that's about to pass very soon (say setting it to 11 when it's 10:51am), it seems to work perfectly fine. I hop in the server to see the server restart message, and then I get kicked from the server when the task completes and it stops the server. But when I set the backupTime value to 3 for 3am, it does not work. It hasn't worked once. I've tried setting it to 03, and I tried setting lastBackup and lastChange to 0, but it does not work at the specified time. There are no warnings or errors in the console at all; it just does not initiate anything for some reason. I'll paste in my full config file for you to check out to see if I screwed anything up. Thank you!

```
# DO NOT CHANGE
configVersion: 11.0
lastBackup: 0
lastChange: 1745588326

backup:
  # (true/false) Automatic backup once in a specified period
  autoBackup: true
  # Set a format for backup file names (see java.time docs). It must contain information about both time and date
  backupFileNameFormat: yyyy-MM-dd HH-mm-ss
  # (Path list) (An example of how to set a list is below) Full directory paths to folders/files that you want to be backed up. Worlds will be backed up automatically, so you do not need to specify world folders there (For example you can specify "plugins", "config") You can also specify all files with "*".
  # addDirectoryToBackup:
  # - 'path1'
  # - 'path2'
  # - ...
  addDirectoryToBackup: ["*"]
  # (Path list) (An example of how to set a list is below) Full directory paths to folders/files that you want to be excluded from backup. If you want to backup everything from the folder1 except some folder1/file1 you can specify folder1 in addDirectoryToBackup and folder1/file1 in excludeDirectoryFromBackup. (The backupsFolder directory will be excluded automatically to prevent the loop)
  # excludeDirectoryFromBackup:
  # - 'path1'
  # - 'path2'
  # - ...
  excludeDirectoryFromBackup: []
  
  # (MINUTES > 0 or -1) Backup period. To change this value you need to set backupTime to -1 and autoBackup to true
  backupPeriod: -1
  # (0 - 23). Automatic backups will be made at this time every day. (backupPeriod will be automatically set to 24 hours). -1 to disable backup time fixation
  backupTime: 10
  
  # (true/false) Sometimes errors may occur while creating a backup. When this option is enabled, such backups will be deleted
  deleteBrokenBackups: true
  # (true/false) The backup will only occur if the world has been changed since the last backup. If the world has not been changed, this backup cycle will be skipped
  skipDuplicateBackup: true
  # (STOP, RESTART, NOTHING) What to do after an automatic backup
  afterBackup: STOP
  
  # (true/false) (True recommended) The backuper will mark all world folders as Read Only to prevent folder changing that may cause the backup crash. True value may cause access denied errors during the backup (you should just ignore that)
  setWorldsReadOnly: false

local:
  # (true/false) Enable local storage to use it via the Backuper
  enabled: true
  # (true/false) With automatic backup, backups will be saved to specified local storage. Works only if 'enabled: true'
  autoBackup: true
  
  # (Path) Full directory where backups will be stored
  backupsFolder: ./plugins/Backuper/Backups
  
  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 10
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0
  
  # (true/false) Should backups be packaged in a zip archive
  zipArchive: true
  # (0 - 9) archive compression level. A higher value may reduce file size, but may also increase the time required to archive and decompress
  zipCompressionLevel: 5

googleDrive:
  # (true/false) Enable Google Drive storage to use it via Backuper
  enabled: false
  # (true/false) With automatic backup, backups will be saved to specified Google Drive. Works only if 'enabled: true'
  autoBackup: true
  
  # Google Drive folder ID where backups will be stored
  backupsFolderId: ''
  # Do you want the Backuper to create its own folder in specified in `backupsFolderId` directory to store backups there
  createBackuperFolder: true
  
  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0
  
  auth:
    # Directory where you want to store your Google authentication tokens
    tokenFolderPath: ./plugins/Backuper/GoogleDrive/tokens

ftp:
  # (true/false) Enable FTP storage to use it via the Backuper
  enabled: false
  # (true/false) With automatic backup, backups will be saved to specified FTP server. Works only if 'enabled: true'
  autoBackup: true
  
  # (Path) FTP server directory where backups will be stored
  backupsFolder: ./
  # (Symbol) Path separator symbol used on FTP SERVER. For example '/' on UNIX systems. (It is usually '/' even on Windows servers, so change it to '\' only if it does not works with '/')
  pathSeparatorSymbol: /
  
  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0
  
  # (true/false) Should backups be packaged in a zip archive
  zipArchive: true
  # (0 - 9) archive compression level. A higher value may reduce file size, but may also increase the time required to archive and decompress
  zipCompressionLevel: 5
  
  auth:
    # (Address) FTP server address
    address: ''
    # (Port) FTP server port
    port: 21
    # (Username) FTP server username to use for authentication
    username: ''
    # (Password) FTP server password to use for authentication
    password: ''

sftp:
  # (true/false) Enable SFTP storage to use it via the Backuper
  enabled: false
  # (true/false) With automatic backup, backups will be saved to specified SFTP server. Works only if 'enabled: true'
  autoBackup: true
  
  # (Path) SFTP server directory where backups will be stored
  backupsFolder: ./
  # (Symbol) Path separator symbol used on SFTP SERVER. For example '/' on UNIX systems and '\' on windows
  pathSeparatorSymbol: /
  
  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0
  
  # (true/false) Should backups be packaged in a zip archive
  zipArchive: true
  # (0 - 9) archive compression level. A higher value may reduce file size, but may also increase the time required to archive and decompress
  zipCompressionLevel: 5
  
  auth:
    # (Address) SFTP server address
    address: ''
    # (Port) SFTP server port
    port: 22
    # (password/key) SFTP server authentication type
    authType: password
    # (Username) SFTP server username to use for authentication
    username: ''
    # (Password) SFTP server password to use for authentication
    password: ''
    # (Absolute Path) Local path to key file if 'authType: key'
    keyFilePath: ''
    # (true/false) Do you want to specify local knownHostsFile?
    useKnownHostsFile: false
    # (Path) Path to local knownHostsFile if 'useKnownHostsFile: true'
    knownHostsFilePath: ''

server:
  # (SECONDS < backupPeriod * 60 or -1) A notification about the server restart will be sent to all players on the server {alertTimeBeforeRestart} seconds before the restart. -1 to disable notifications
  alertTimeBeforeRestart: 60
  # (true/false) Notifications will be sent only if the server will be restarted or stopped after the backup
  alertOnlyServerRestart: true
  # (String) Backup alert message. (%d is a seconds number placeholder)
  alertBackupMessage: Server will be backed up in %d second(s)
  # (String) Backup and restart alert message. (%d is a seconds number placeholder)
  alertBackupRestartMessage: Server will be restarted in about 10 minutes. Don't fly
    over lava!
  
  # (Path) Size cache file
  sizeCacheFile: ./plugins/Backuper/sizeCache.json
  
  # (true/false) Check for new versions of the Backuper to stay up to date
  checkUpdates: true
  
  # (true/false) Better logging (Some statistic and other information for debugging, you probably don't need it)
  betterLogging: false
```

P.S. - every time the backup has been tried, the world has absolutely been changed since the last backup. Like, 100% guaranteed, so it shouldn't be skipping due to that reason. Also, the lastBackup number being set to 0 is a recent change. The plugin wasn't working prior to that being changed, either.

P.S.S. Sorry, should've included this originally:
Minecraft v 1.21.4, PaperMC build 226 (happened on build 224 as well)
Plugins:
Backuper-3.3.0
DHS-0.8.1_for_MC-1.21.4
DiscordSRV-Build-1.29.0
EssentialsX-2.21.1-dev+13-be3e641
floodgate-spigot
Geyser-Spigot
ViaVersion-5.3.2

Also, this issue was occurring before I installed anything past EssentialsX IIRC. I believe that all of the other plugins were added after the issue originally happened.
